### ISSUE TITLE
Where is the waymo data of modes/16^?

### ISSUE THREAD

**Issue by fdy61** [rasd3/TODA#2]

**Comment by rasd3** [comment]
Hi

I used the LiDARDistill code (https://github.com/weiyithu/LiDAR-Distillation) for 16-channel downsampling. I plan to update this later, but if it’s urgent, please refer to the beam downsampling code in the getting_started.md file on the GitHub page

**Comment by fdy61** [comment]
Thanks. But Nus are of 32beams,  why you use 16 instead of 32?

**Comment by rasd3** [comment]
As mentioned in the paper, the FOV of nuScenes is twice as wide as that of Waymo. Consequently, from a density perspective—meaning the number of beams per unit area—it effectively reduces to one-fourth, resulting in a similar point distribution. This is why we used a 16-channel setup.

**Comment by fdy61** [comment]
Thank you. In the code of  LiDARDistill, 'ri_index' is set to 0 for only the first return in convert_range_image_to_point_cloud( https://github.com/weiyithu/LiDAR-Distillation/blob/1c222ca89685b2625260330ba137c760a1bd0e60/pcdet/datasets/waymo/waymo_utils.py#L63), whiles other codes set the ri_index to (0, 1)(TODA or SSDA3D). Does it matters?

**Comment by rasd3** [comment]
I’m not too sure about this. I just remember that create_data is from the TODA code, and the 16^ was generated using LiDARDistill.
